import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";

vi.mock("@/lib/apiClient", () => ({
  apiClient: { GET: vi.fn(), POST: vi.fn() },
  API_URL: "http://localhost:8010",
}));

import { ProposedFixPanel } from "@/components/ProposedFixPanel";
import { apiClient } from "@/lib/apiClient";

const BASE_PROPOSED_CHANGE = {
  id: "pc-1",
  finding_id: "f-1",
  file_id: "file-1",
  explanation: "Mock proposed fix for `unsafe-division` (bug/high): add a zero guard.",
  updated_content: "export function divide(a, b) {\n  if (b === 0) return 0;\n  return a / b;\n}\n",
  test_file_path: null,
  test_file_content: null,
  generated_by: "mock",
  status: "draft",
  pr_url: null,
  pr_number: null,
  published_at: null,
};

function renderPanel() {
  return render(
    <ProposedFixPanel
      orgId="org-1"
      repoId="repo-1"
      findingId="f-1"
      filePath="src/utils/math.ts"
      language="typescript"
      originalContent="export function divide(a, b) {\n  return a / b;\n}\n"
    />,
  );
}

describe("ProposedFixPanel", () => {
  it("shows a 'Propose fix' button before anything has been proposed", () => {
    renderPanel();
    expect(screen.getByText("Propose fix")).toBeInTheDocument();
  });

  it("proposes a fix and renders the explanation and side-by-side content", async () => {
    vi.mocked(apiClient.POST).mockResolvedValue({
      data: BASE_PROPOSED_CHANGE,
      error: undefined,
    } as never);

    renderPanel();
    fireEvent.click(screen.getByText("Propose fix"));

    expect(apiClient.POST).toHaveBeenCalledWith(
      "/api/organizations/{org_id}/repositories/{repo_id}/findings/{finding_id}/propose-fix",
      { params: { path: { org_id: "org-1", repo_id: "repo-1", finding_id: "f-1" } } },
    );

    await waitFor(() => {
      expect(screen.getByText(/Mock proposed fix for/)).toBeInTheDocument();
    });
    expect(screen.getByText(/generated by: mock/)).toBeInTheDocument();
    expect(screen.getByText("Publish as draft PR")).toBeInTheDocument();
  });

  it("shows the propose-fix error message when it fails", async () => {
    vi.mocked(apiClient.POST).mockResolvedValue({
      data: undefined,
      error: { detail: "No file found for this finding" },
    } as never);

    renderPanel();
    fireEvent.click(screen.getByText("Propose fix"));

    await waitFor(() => {
      expect(screen.getByText("No file found for this finding")).toBeInTheDocument();
    });
  });

  it("requires confirmation before publishing, then publishes and shows the PR link", async () => {
    vi.mocked(apiClient.POST).mockResolvedValueOnce({
      data: BASE_PROPOSED_CHANGE,
      error: undefined,
    } as never);

    renderPanel();
    fireEvent.click(screen.getByText("Propose fix"));
    await waitFor(() => expect(screen.getByText("Publish as draft PR")).toBeInTheDocument());

    fireEvent.click(screen.getByText("Publish as draft PR"));
    expect(screen.getByText(/This creates a real branch/)).toBeInTheDocument();
    vi.mocked(apiClient.POST).mockClear(); // clicking "Publish" itself makes no request — only "Confirm" does

    vi.mocked(apiClient.POST).mockResolvedValueOnce({
      data: { pr_url: "https://github.com/acme/widgets/pull/7", pr_number: 7 },
      error: undefined,
    } as never);

    fireEvent.click(screen.getByText("Confirm publish"));

    expect(apiClient.POST).toHaveBeenLastCalledWith(
      "/api/organizations/{org_id}/repositories/{repo_id}/proposed-changes/{proposed_change_id}/publish",
      { params: { path: { org_id: "org-1", repo_id: "repo-1", proposed_change_id: "pc-1" } } },
    );

    await waitFor(() => {
      expect(screen.getByText("pull request #7")).toBeInTheDocument();
    });
    expect(screen.queryByText("Publish as draft PR")).not.toBeInTheDocument();
  });

  it("shows a 409 staleness error from publish without changing status", async () => {
    vi.mocked(apiClient.POST).mockResolvedValueOnce({
      data: BASE_PROPOSED_CHANGE,
      error: undefined,
    } as never);

    renderPanel();
    fireEvent.click(screen.getByText("Propose fix"));
    await waitFor(() => expect(screen.getByText("Publish as draft PR")).toBeInTheDocument());

    fireEvent.click(screen.getByText("Publish as draft PR"));

    vi.mocked(apiClient.POST).mockResolvedValueOnce({
      data: undefined,
      error: { detail: "src/utils/math.ts on acme/widgets@main has changed since this fix was generated" },
    } as never);
    fireEvent.click(screen.getByText("Confirm publish"));

    await waitFor(() => {
      expect(screen.getByText(/has changed since this fix was generated/)).toBeInTheDocument();
    });
    expect(screen.getByText("Publish as draft PR")).toBeInTheDocument();
  });
});
