import { test, expect } from "@playwright/test";

test.setTimeout(120_000);

test("register through indexing, findings, propose-fix, publish, and PR review", async ({
  page,
}) => {
  const unique = Date.now();
  const email = `e2e-${unique}@example.com`;
  const orgName = `E2E Org ${unique}`;

  let orgId = "";
  let repoId = "";

  await test.step("register", async () => {
    await page.goto("/register");
    await page.getByPlaceholder("Full name").fill("E2E Tester");
    await page.getByPlaceholder("Email").fill(email);
    await page.getByPlaceholder("Password").fill("hunter22");
    await page.getByRole("button", { name: "Create account" }).click();
    await page.waitForURL(/\/orgs$/);
  });

  await test.step("create organization", async () => {
    await page.goto("/orgs/new");
    await page.getByPlaceholder("Organization name").fill(orgName);
    await page.getByRole("button", { name: "Create organization" }).click();
    await page.waitForURL(
      (url) => /\/orgs\/[^/]+$/.test(url.pathname) && !url.pathname.endsWith("/new"),
    );
    orgId = page.url().split("/orgs/")[1];
  });

  await test.step("connect GitHub (mock) and add the demo repo", async () => {
    await page.getByRole("button", { name: "Connect GitHub (mock)" }).click();
    const addButton = page.getByRole("button", { name: "Add" });
    await addButton.waitFor();
    await addButton.click();

    // Scope to an actual repo link, not the plain <span> in the
    // "Connect GitHub" available-repos list, which also contains the repo
    // name as text but isn't a link.
    const repoLink = page.locator('a[href*="/repos/"]').first();
    await repoLink.waitFor();
    await repoLink.click();
    await page.waitForURL(/\/repos\/[^/]+$/);
    repoId = page.url().split("/repos/")[1];
  });

  await test.step("run indexing", async () => {
    await page.getByRole("button", { name: "Run indexing" }).click();
    await expect(page.getByText("Indexed")).toBeVisible({ timeout: 30_000 });
  });

  await test.step("explore files", async () => {
    await page.getByRole("link", { name: "Explore files" }).click();
    await page.waitForURL(/\/files$/);
    await page.getByText("math.ts").first().click();
    await expect(page.getByText(/divide/).first()).toBeVisible();
  });

  await test.step("ask a question with no keyword overlap", async () => {
    await page.goto(`/orgs/${orgId}/repos/${repoId}`);
    await page.getByRole("link", { name: "Ask a question" }).click();
    await page.waitForURL(/\/ask$/);
    await page
      .getByPlaceholder("Ask a question about this repository...")
      .fill("how do I split a number into pieces?");
    await page.getByRole("button", { name: "Ask" }).click();
    await expect(page.getByText(/math\.ts/).first()).toBeVisible({ timeout: 15_000 });
  });

  await test.step("run analysis", async () => {
    await page.goto(`/orgs/${orgId}/repos/${repoId}/findings`);
    await page.getByRole("button", { name: "Run analysis" }).click();
    await expect(page.getByText(/Unguarded division/i).first()).toBeVisible({
      timeout: 30_000,
    });
  });

  await test.step("open a finding, explain it with AI, and propose a fix", async () => {
    await page.getByText(/Unguarded division/i).first().click();
    await page.waitForURL(/\/findings\/[^/]+$/);

    await page.getByRole("button", { name: "Explain with AI" }).click();
    await expect(page.getByText(/Mock explanation for `unsafe-division`/i)).toBeVisible({
      timeout: 15_000,
    });

    await page.getByRole("button", { name: "Propose fix" }).click();
    await expect(page.getByText(/generated by: mock/i)).toBeVisible({ timeout: 15_000 });
  });

  await test.step("attempt to publish, expect a graceful not-configured error", async () => {
    await page.getByRole("button", { name: "Publish as draft PR" }).click();
    await page.getByRole("button", { name: "Confirm publish" }).click();
    await expect(page.getByText(/No publish target configured/i)).toBeVisible({
      timeout: 10_000,
    });
  });

  await test.step("dismiss a different finding", async () => {
    await page.goto(`/orgs/${orgId}/repos/${repoId}/findings`);
    const findingLinks = page.locator('a[href*="/findings/"]');
    const count = await findingLinks.count();
    let dismissedOne = false;
    for (let i = 0; i < count; i++) {
      const text = await findingLinks.nth(i).innerText();
      if (!text.includes("Unguarded division")) {
        await findingLinks.nth(i).click();
        dismissedOne = true;
        break;
      }
    }
    expect(dismissedOne).toBe(true);

    await page.waitForURL(/\/findings\/[^/]+$/);
    await page
      .getByPlaceholder(/Why is this being dismissed/i)
      .fill("False positive — dismissed by the E2E suite.");
    await page.getByRole("button", { name: "Dismiss finding" }).click();
    await expect(page.getByText("dismissed")).toBeVisible({ timeout: 10_000 });
  });

  await test.step("attempt a PR review, expect a graceful not-configured error", async () => {
    await page.goto(`/orgs/${orgId}`);
    await page.getByLabel("PR number").fill("1");
    await page.getByRole("button", { name: "Review PR" }).click();
    await page.getByRole("button", { name: "Confirm review" }).click();
    await expect(page.getByText(/No target repo configured/i)).toBeVisible({
      timeout: 10_000,
    });
  });

  await test.step("PR review history is empty (the attempt above never persisted)", async () => {
    await page.getByRole("link", { name: "View past reviews" }).click();
    await page.waitForURL(/\/pr-reviews$/);
    await expect(page.getByText("No PR reviews yet.")).toBeVisible({ timeout: 10_000 });
  });
});
