"use client";

import { useState } from "react";

import { apiClient } from "@/lib/apiClient";
import { extractErrorDetail } from "@/lib/proposedChanges";

interface FindingExplanation {
  id: string;
  explanation: string;
  generated_by: string;
}

export function FindingExplanationPanel({
  orgId,
  repoId,
  findingId,
}: {
  orgId: string;
  repoId: string;
  findingId: string;
}) {
  const [explanation, setExplanation] = useState<FindingExplanation | null>(null);
  const [isExplaining, setIsExplaining] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  async function handleExplain() {
    setIsExplaining(true);
    setErrorMessage(null);
    const { data, error } = await apiClient.POST(
      "/api/organizations/{org_id}/repositories/{repo_id}/findings/{finding_id}/explain",
      { params: { path: { org_id: orgId, repo_id: repoId, finding_id: findingId } } },
    );
    setIsExplaining(false);
    if (error) {
      setErrorMessage(extractErrorDetail(error) ?? "Failed to generate an explanation.");
      return;
    }
    setExplanation(data);
  }

  return (
    <div className="mb-6 rounded border border-gray-800 p-4">
      <h2 className="mb-3 text-sm font-medium text-gray-500">AI explanation</h2>

      {!explanation && (
        <button
          onClick={handleExplain}
          disabled={isExplaining}
          className="rounded bg-blue-900 px-4 py-2 text-sm text-white hover:bg-blue-800 disabled:opacity-50"
        >
          {isExplaining ? "Explaining..." : "Explain with AI"}
        </button>
      )}

      {explanation && (
        <div className="flex flex-col gap-2">
          <p className="text-gray-300">{explanation.explanation}</p>
          <span className="text-xs text-gray-600">generated by: {explanation.generated_by}</span>
        </div>
      )}

      {errorMessage && <p className="mt-3 text-sm text-red-400">{errorMessage}</p>}
    </div>
  );
}
