"use client";

import { Sparkles } from "lucide-react";
import { useState } from "react";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { apiClient } from "@/lib/apiClient";
import { extractErrorDetail } from "@/lib/proposedChanges";

interface FindingExplanation {
  id: string;
  explanation: string;
  generated_by: string;
}

export function FindingExplanationPanel({
  orgId,
  repoId,
  findingId,
}: {
  orgId: string;
  repoId: string;
  findingId: string;
}) {
  const [explanation, setExplanation] = useState<FindingExplanation | null>(null);
  const [isExplaining, setIsExplaining] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  async function handleExplain() {
    setIsExplaining(true);
    setErrorMessage(null);
    const { data, error } = await apiClient.POST(
      "/api/organizations/{org_id}/repositories/{repo_id}/findings/{finding_id}/explain",
      { params: { path: { org_id: orgId, repo_id: repoId, finding_id: findingId } } },
    );
    setIsExplaining(false);
    if (error) {
      setErrorMessage(extractErrorDetail(error) ?? "Failed to generate an explanation.");
      return;
    }
    setExplanation(data);
  }

  return (
    <Card className="mb-6 gap-3 p-4 shadow-none">
      <CardHeader className="p-0">
        <CardTitle className="text-sm font-medium text-muted-foreground">AI explanation</CardTitle>
      </CardHeader>
      <CardContent className="p-0">
        {!explanation && (
          <Button size="sm" variant="secondary" onClick={handleExplain} disabled={isExplaining}>
            <Sparkles className="size-3.5" />
            {isExplaining ? "Explaining..." : "Explain with AI"}
          </Button>
        )}

        {explanation && (
          <div className="flex flex-col gap-2">
            <p className="text-sm text-foreground/90">{explanation.explanation}</p>
            <span className="text-xs text-muted-foreground">
              generated by: {explanation.generated_by}
            </span>
          </div>
        )}

        {errorMessage && <p className="mt-3 text-sm text-destructive" role="alert">{errorMessage}</p>}
      </CardContent>
    </Card>
  );
}
