"use client";

import { useState } from "react";

import { apiClient } from "@/lib/apiClient";
import {
  canPublish,
  extractErrorDetail,
  publishConfirmationMessage,
  type ProposedChange,
} from "@/lib/proposedChanges";
import { SourceViewer } from "@/components/SourceViewer";

export function ProposedFixPanel({
  orgId,
  repoId,
  findingId,
  filePath,
  language,
  originalContent,
}: {
  orgId: string;
  repoId: string;
  findingId: string;
  filePath: string;
  language: string;
  originalContent: string;
}) {
  const [proposedChange, setProposedChange] = useState<ProposedChange | null>(null);
  const [isProposing, setIsProposing] = useState(false);
  const [isPublishing, setIsPublishing] = useState(false);
  const [confirmingPublish, setConfirmingPublish] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  async function handlePropose() {
    setIsProposing(true);
    setErrorMessage(null);
    const { data, error } = await apiClient.POST(
      "/api/organizations/{org_id}/repositories/{repo_id}/findings/{finding_id}/propose-fix",
      { params: { path: { org_id: orgId, repo_id: repoId, finding_id: findingId } } },
    );
    setIsProposing(false);
    if (error) {
      setErrorMessage(extractErrorDetail(error) ?? "Failed to propose a fix.");
      return;
    }
    setProposedChange(data);
  }

  async function handlePublish() {
    if (!proposedChange) return;
    setIsPublishing(true);
    setErrorMessage(null);
    const { data, error } = await apiClient.POST(
      "/api/organizations/{org_id}/repositories/{repo_id}/proposed-changes/{proposed_change_id}/publish",
      {
        params: {
          path: { org_id: orgId, repo_id: repoId, proposed_change_id: proposedChange.id },
        },
      },
    );
    setIsPublishing(false);
    setConfirmingPublish(false);
    if (error) {
      setErrorMessage(extractErrorDetail(error) ?? "Failed to publish.");
      return;
    }
    setProposedChange({
      ...proposedChange,
      status: "published",
      pr_url: data.pr_url,
      pr_number: data.pr_number,
    });
  }

  return (
    <div className="mb-6 rounded border border-gray-800 p-4">
      <h2 className="mb-3 text-sm font-medium text-gray-500">Proposed fix</h2>

      {!proposedChange && (
        <button
          onClick={handlePropose}
          disabled={isProposing}
          className="rounded bg-blue-900 px-4 py-2 text-sm text-white hover:bg-blue-800 disabled:opacity-50"
        >
          {isProposing ? "Generating fix..." : "Propose fix"}
        </button>
      )}

      {proposedChange && (
        <div className="flex flex-col gap-4">
          <p className="text-gray-300">{proposedChange.explanation}</p>
          <span className="text-xs text-gray-600">
            generated by: {proposedChange.generated_by}
          </span>

          <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
            <div>
              <h3 className="mb-1 text-xs font-medium text-gray-500">Original</h3>
              <SourceViewer content={originalContent} language={language} />
            </div>
            <div>
              <h3 className="mb-1 text-xs font-medium text-gray-500">Proposed</h3>
              <SourceViewer content={proposedChange.updated_content} language={language} />
            </div>
          </div>

          {proposedChange.test_file_path && proposedChange.test_file_content && (
            <div>
              <h3 className="mb-1 text-xs font-medium text-gray-500">
                New test: {proposedChange.test_file_path}
              </h3>
              <SourceViewer content={proposedChange.test_file_content} language={language} />
            </div>
          )}

          {proposedChange.status === "published" && proposedChange.pr_url && (
            <p className="text-sm text-green-400">
              Published:{" "}
              <a
                href={proposedChange.pr_url}
                target="_blank"
                rel="noreferrer"
                className="underline"
              >
                pull request #{proposedChange.pr_number}
              </a>
            </p>
          )}

          {canPublish(proposedChange) && !confirmingPublish && (
            <button
              onClick={() => setConfirmingPublish(true)}
              className="self-start rounded bg-green-900 px-4 py-2 text-sm text-white hover:bg-green-800"
            >
              Publish as draft PR
            </button>
          )}

          {canPublish(proposedChange) && confirmingPublish && (
            <div className="flex flex-col gap-2 rounded border border-yellow-900 bg-yellow-950/30 p-3">
              <p className="text-sm text-yellow-200">{publishConfirmationMessage(filePath)}</p>
              <div className="flex gap-2">
                <button
                  onClick={handlePublish}
                  disabled={isPublishing}
                  className="rounded bg-green-900 px-4 py-2 text-sm text-white hover:bg-green-800 disabled:opacity-50"
                >
                  {isPublishing ? "Publishing..." : "Confirm publish"}
                </button>
                <button
                  onClick={() => setConfirmingPublish(false)}
                  disabled={isPublishing}
                  className="rounded border border-gray-700 px-4 py-2 text-sm text-gray-300 hover:bg-gray-800"
                >
                  Cancel
                </button>
              </div>
            </div>
          )}
        </div>
      )}

      {errorMessage && <p className="mt-3 text-sm text-red-400">{errorMessage}</p>}
    </div>
  );
}
