"use client";

import { useState } from "react";

import { SourceViewer } from "@/components/SourceViewer";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { apiClient } from "@/lib/apiClient";
import {
  canPublish,
  extractErrorDetail,
  publishConfirmationMessage,
  type ProposedChange,
} from "@/lib/proposedChanges";

export function ProposedFixPanel({
  orgId,
  repoId,
  findingId,
  filePath,
  language,
  originalContent,
}: {
  orgId: string;
  repoId: string;
  findingId: string;
  filePath: string;
  language: string;
  originalContent: string;
}) {
  const [proposedChange, setProposedChange] = useState<ProposedChange | null>(null);
  const [isProposing, setIsProposing] = useState(false);
  const [isPublishing, setIsPublishing] = useState(false);
  const [confirmingPublish, setConfirmingPublish] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);

  async function handlePropose() {
    setIsProposing(true);
    setErrorMessage(null);
    const { data, error } = await apiClient.POST(
      "/api/organizations/{org_id}/repositories/{repo_id}/findings/{finding_id}/propose-fix",
      { params: { path: { org_id: orgId, repo_id: repoId, finding_id: findingId } } },
    );
    setIsProposing(false);
    if (error) {
      setErrorMessage(extractErrorDetail(error) ?? "Failed to propose a fix.");
      return;
    }
    setProposedChange(data);
  }

  async function handlePublish() {
    if (!proposedChange) return;
    setIsPublishing(true);
    setErrorMessage(null);
    const { data, error } = await apiClient.POST(
      "/api/organizations/{org_id}/repositories/{repo_id}/proposed-changes/{proposed_change_id}/publish",
      {
        params: {
          path: { org_id: orgId, repo_id: repoId, proposed_change_id: proposedChange.id },
        },
      },
    );
    setIsPublishing(false);
    setConfirmingPublish(false);
    if (error) {
      setErrorMessage(extractErrorDetail(error) ?? "Failed to publish.");
      return;
    }
    setProposedChange({
      ...proposedChange,
      status: "published",
      pr_url: data.pr_url,
      pr_number: data.pr_number,
    });
  }

  return (
    <Card className="mb-6 gap-3 p-4 shadow-none">
      <CardHeader className="p-0">
        <CardTitle className="text-sm font-medium text-muted-foreground">Proposed fix</CardTitle>
      </CardHeader>
      <CardContent className="p-0">
        {!proposedChange && (
          <Button size="sm" variant="secondary" onClick={handlePropose} disabled={isProposing}>
            {isProposing ? "Generating fix..." : "Propose fix"}
          </Button>
        )}

        {proposedChange && (
          <div className="flex flex-col gap-4">
            <p className="text-sm text-foreground/90">{proposedChange.explanation}</p>
            <span className="text-xs text-muted-foreground">
              generated by: {proposedChange.generated_by}
            </span>

            <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
              <div>
                <h3 className="mb-1 text-xs font-medium text-muted-foreground">Original</h3>
                <SourceViewer content={originalContent} language={language} />
              </div>
              <div>
                <h3 className="mb-1 text-xs font-medium text-muted-foreground">Proposed</h3>
                <SourceViewer content={proposedChange.updated_content} language={language} />
              </div>
            </div>

            {proposedChange.test_file_path && proposedChange.test_file_content && (
              <div>
                <h3 className="mb-1 text-xs font-medium text-muted-foreground">
                  New test: {proposedChange.test_file_path}
                </h3>
                <SourceViewer content={proposedChange.test_file_content} language={language} />
              </div>
            )}

            {proposedChange.status === "published" && proposedChange.pr_url && (
              <p className="text-sm text-emerald-400">
                Published:{" "}
                <a
                  href={proposedChange.pr_url}
                  target="_blank"
                  rel="noreferrer"
                  className="underline"
                >
                  pull request #{proposedChange.pr_number}
                </a>
              </p>
            )}

            {canPublish(proposedChange) && (
              <Button
                size="sm"
                onClick={() => setConfirmingPublish(true)}
                className="self-start"
              >
                Publish as draft PR
              </Button>
            )}

            <AlertDialog open={confirmingPublish} onOpenChange={setConfirmingPublish}>
              <AlertDialogContent>
                <AlertDialogHeader>
                  <AlertDialogTitle>Publish this fix as a draft PR?</AlertDialogTitle>
                  <AlertDialogDescription>
                    {publishConfirmationMessage(filePath)}
                  </AlertDialogDescription>
                </AlertDialogHeader>
                <AlertDialogFooter>
                  <AlertDialogCancel disabled={isPublishing}>Cancel</AlertDialogCancel>
                  <AlertDialogAction onClick={handlePublish} disabled={isPublishing}>
                    {isPublishing ? "Publishing..." : "Confirm publish"}
                  </AlertDialogAction>
                </AlertDialogFooter>
              </AlertDialogContent>
            </AlertDialog>
          </div>
        )}

        {errorMessage && (
          <p className="mt-3 text-sm text-destructive" role="alert">
            {errorMessage}
          </p>
        )}
      </CardContent>
    </Card>
  );
}
